### PR TITLE
Add new function

### PR DESCRIPTION
**Pull request by darhanger**
https://github.com/scizzydo/ni/issues/33

### CODE REVIEW

**Comment by scizzydo** [comment]
Please update the mainui file with the latest git commit for beta branch before merging

**Comment by scizzydo** [comment]
I still don't see the other commit to patch-7 for the commit hash in mainui.lua

**Comment by darhanger** [comment]
idk how make this. Cuz try it make yesterday from GitHub app and seems its not work .

**Comment by scizzydo** [comment]
You need to git push to the branch "patch-7"

**Comment by darhanger** [comment]
idk. Maybe make this

**Review by scizzydo — CHANGES_REQUESTED** [review]
The release still needs to be on 46, all I asked for was the commit change which needs to be "64b72dfb5833b51f046824987231eec3227ed9b0" and then I'll merge.

**Pull request merged**
